---
name: build
on: [push, pull_request]
jobs:
  goreleaser:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Set up Go
        uses: actions/setup-go@v1
        with:
          go-version: '1.13.x'
      - name: Build
        run: go build ./...
      - name: Test
        run: go test -v ./...
#     - name: Run GoReleaser
#       uses: goreleaser/goreleaser-action@v1
#       with:
#         version: latest
#         args: release
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
